// src/constants/navPresets.js
import { NAV_STYLE_DEFAULT, normalizeNavStyle } from "../utils/navStyle";

export const NAV_STYLE_PRESETS = [
  {
    id: "brand-pill",
    name: "Brand Pill",
    description: "Rounded pill button using the site primary color.",
    style: {
      ...NAV_STYLE_DEFAULT,
    },
  },
  {
    id: "underline-classic",
    name: "Classic Underline",
    description: "Minimal underline menu with bold active indicator.",
    style: {
      variant: "underline",
      font_weight: 600,
      text_transform: "uppercase",
      padding_x: 12,
      padding_y: 6,
      item_spacing: 16,
      border_radius: 0,
      bg: "transparent",
      bg_hover: "transparent",
      text: "var(--sched-text, #1f2937)",
      text_hover: "var(--sched-primary)",
      active_bg: "var(--sched-primary)",
      active_text: "var(--sched-primary)",
      shadow: "none",
    },
  },
  {
    id: "overline-classic",
    name: "Overline Classic",
    description: "Underline style but with an accent line above the label.",
    style: {
      variant: "overline",
      font_weight: 600,
      text_transform: "uppercase",
      padding_x: 12,
      padding_y: 6,
      item_spacing: 16,
      border_radius: 0,
      bg: "transparent",
      bg_hover: "transparent",
      text: "var(--sched-text, #1f2937)",
      text_hover: "var(--sched-primary)",
      active_bg: "var(--sched-primary)",
      active_text: "var(--sched-primary)",
      shadow: "none",
    },
  },
  {
    id: "doubleline-classic",
    name: "Double Line",
    description: "Clean top + bottom lines with strong active state.",
    style: {
      variant: "doubleline",
      font_weight: 600,
      text_transform: "uppercase",
      padding_x: 12,
      padding_y: 6,
      item_spacing: 16,
      border_radius: 0,
      bg: "transparent",
      bg_hover: "transparent",
      text: "var(--sched-text, #1f2937)",
      text_hover: "var(--sched-primary)",
      active_bg: "var(--sched-primary)",
      active_text: "var(--sched-primary)",
      shadow: "none",
    },
  },
  {
    id: "ink-underline",
    name: "Ink Underline",
    description: "Modern underline with slimmer spacing and muted text.",
    style: {
      variant: "underline",
      font_weight: 500,
      text_transform: "none",
      padding_x: 10,
      padding_y: 4,
      item_spacing: 14,
      border_radius: 0,
      bg: "transparent",
      bg_hover: "transparent",
      text: "var(--sched-text, #0f172a)",
      text_hover: "var(--sched-primary, #6366F1)",
      active_bg: "var(--sched-primary, #6366F1)",
      active_text: "var(--sched-primary, #6366F1)",
      shadow: "none",
    },
  },
  {
    id: "soft-ghost",
    name: "Soft Ghost",
    description: "Minimal ghost outline with soft rounded corners.",
    style: {
      variant: "ghost",
      font_weight: 500,
      text_transform: "none",
      padding_x: 16,
      padding_y: 8,
      item_spacing: 12,
      border_radius: 14,
      bg: "rgba(255,255,255,0.0)",
      bg_hover: "rgba(148,163,184,0.16)",
      text: "var(--sched-text, #1f2937)",
      text_hover: "var(--sched-text, #1f2937)",
      active_bg: "rgba(15,23,42,0.08)",
      active_text: "var(--sched-text, #1f2937)",
      shadow: "none",
    },
  },
  {
    id: "glass-outline",
    name: "Glass Outline",
    description: "Transparent outline with a subtle glass hover.",
    style: {
      variant: "ghost",
      font_weight: 600,
      text_transform: "uppercase",
      padding_x: 18,
      padding_y: 10,
      item_spacing: 14,
      border_radius: 999,
      bg: "rgba(255,255,255,0.08)",
      bg_hover: "rgba(255,255,255,0.18)",
      text: "#ffffff",
      text_hover: "#ffffff",
      active_bg: "rgba(255,255,255,0.28)",
      active_text: "#ffffff",
      shadow: "0 12px 24px rgba(15,23,42,0.20)",
    },
  },
  {
    id: "line-tab",
    name: "Line Tab",
    description: "Compact text tabs with an understated active line.",
    style: {
      variant: "underline",
      font_weight: 600,
      text_transform: "none",
      padding_x: 8,
      padding_y: 4,
      item_spacing: 12,
      border_radius: 0,
      bg: "transparent",
      bg_hover: "transparent",
      text: "var(--sched-text, #111827)",
      text_hover: "var(--sched-primary, #6366F1)",
      active_bg: "var(--sched-primary, #6366F1)",
      active_text: "var(--sched-primary, #6366F1)",
      shadow: "none",
    },
  },
  {
    id: "soft-pill",
    name: "Soft Pill",
    description: "Rounded pills with gentle background tint.",
    style: {
      variant: "pill",
      font_weight: 600,
      text_transform: "none",
      padding_x: 18,
      padding_y: 8,
      item_spacing: 14,
      border_radius: 999,
      bg: "rgba(15,23,42,0.06)",
      bg_hover: "rgba(15,23,42,0.12)",
      text: "var(--sched-text, #111827)",
      text_hover: "var(--sched-text, #111827)",
      active_bg: "rgba(15,23,42,0.18)",
      active_text: "var(--sched-text, #111827)",
      shadow: "none",
    },
  },
  {
    id: "contrast-link",
    name: "Contrast Link",
    description: "Text-only links with higher contrast hover.",
    style: {
      variant: "link",
      font_weight: 600,
      text_transform: "uppercase",
      padding_x: 10,
      padding_y: 6,
      item_spacing: 16,
      border_radius: 0,
      bg: "transparent",
      bg_hover: "transparent",
      text: "var(--sched-text, #0f172a)",
      text_hover: "var(--sched-primary, #6366F1)",
      active_bg: "transparent",
      active_text: "var(--sched-primary, #6366F1)",
      shadow: "none",
      divider: null,
    },
  },
  {
    id: "glass-ghost",
    name: "Glass Ghost",
    description: "Semi-transparent ghost buttons with subtle backdrop.",
    style: {
      variant: "ghost",
      font_weight: 600,
      text_transform: "none",
      padding_x: 18,
      padding_y: 10,
      item_spacing: 14,
      border_radius: 18,
      bg: "rgba(255,255,255,0.08)",
      bg_hover: "rgba(255,255,255,0.16)",
      text: "#ffffff",
      text_hover: "#ffffff",
      active_bg: "rgba(255,255,255,0.22)",
      active_text: "#ffffff",
      shadow: "0 16px 32px rgba(15,23,42,0.28)",
    },
  },
  {
    id: "solid-button",
    name: "Solid Button",
    description: "Squared solid buttons with subtle border.",
    style: {
      variant: "button",
      font_weight: 600,
      text_transform: "none",
      padding_x: 18,
      padding_y: 12,
      item_spacing: 14,
      border_radius: 10,
      bg: "var(--sched-primary, #6366F1)",
      bg_hover: "#4F46E5",
      text: "#ffffff",
      text_hover: "#ffffff",
      active_bg: "#4338CA",
      active_text: "#ffffff",
      shadow: "0 14px 28px rgba(15,23,42,0.20)",
      divider: "rgba(255,255,255,0.2)",
    },
  },
  {
    id: "minimal-link",
    name: "Minimal Link",
    description: "Text-only navigation for ultra-lightweight headers.",
    style: {
      variant: "link",
      font_weight: 500,
      text_transform: "none",
      padding_x: 12,
      padding_y: 6,
      item_spacing: 18,
      border_radius: 4,
      bg: "transparent",
      bg_hover: "transparent",
      text: "var(--sched-text, #0f172a)",
      text_hover: "var(--sched-primary, #6366F1)",
      active_bg: "transparent",
      active_text: "var(--sched-primary, #6366F1)",
      shadow: "none",
      divider: null,
    },
  },
];

export const NAV_COLOR_PRESETS = [
  {
    id: "sunset",
    name: "Sunset",
    colors: {
      bg: "#F97316",
      bg_hover: "#EA580C",
      text: "#ffffff",
      text_hover: "#ffffff",
      active_bg: "rgba(249,115,22,0.20)",
      active_text: "#C2410C",
    },
    swatch: ["#F97316", "#EA580C"],
  },
  {
    id: "berry",
    name: "Berry",
    colors: {
      bg: "#6C5CE7",
      bg_hover: "#5A4AD1",
      text: "#ffffff",
      text_hover: "#ffffff",
      active_bg: "rgba(108,92,231,0.18)",
      active_text: "#4C1D95",
    },
    swatch: ["#6C5CE7", "#5A4AD1"],
  },
  {
    id: "ocean",
    name: "Ocean",
    colors: {
      bg: "#0EA5E9",
      bg_hover: "#0284C7",
      text: "#0F172A",
      text_hover: "#0F172A",
      active_bg: "rgba(14,165,233,0.20)",
      active_text: "#0EA5E9",
    },
    swatch: ["#0EA5E9", "#0284C7"],
  },
  {
    id: "charcoal",
    name: "Charcoal",
    colors: {
      bg: "#1F2937",
      bg_hover: "#111827",
      text: "#F8FAFC",
      text_hover: "#F8FAFC",
      active_bg: "rgba(15,23,42,0.25)",
      active_text: "#F8FAFC",
    },
    swatch: ["#1F2937", "#111827"],
  },
  {
    id: "forest",
    name: "Forest",
    colors: {
      bg: "#047857",
      bg_hover: "#065f46",
      text: "#F0FDF4",
      text_hover: "#F0FDF4",
      active_bg: "rgba(4,120,87,0.24)",
      active_text: "#D1FAE5",
    },
    swatch: ["#047857", "#065f46"],
  },
  {
    id: "rose",
    name: "Rose",
    colors: {
      bg: "#F43F5E",
      bg_hover: "#E11D48",
      text: "#FFFFFF",
      text_hover: "#FFFFFF",
      active_bg: "rgba(244,63,94,0.22)",
      active_text: "#FCE7F3",
    },
    swatch: ["#F43F5E", "#E11D48"],
  },
  {
    id: "slate",
    name: "Slate",
    colors: {
      bg: "#334155",
      bg_hover: "#1e293b",
      text: "#e2e8f0",
      text_hover: "#ffffff",
      active_bg: "rgba(51,65,85,0.28)",
      active_text: "#e2e8f0",
    },
    swatch: ["#334155", "#1e293b"],
  },
];

export const NAV_SHADOW_PRESETS = [
  { id: "none", name: "No shadow", value: "none" },
  {
    id: "soft",
    name: "Soft float",
    value: "0 16px 32px rgba(15,23,42,0.18)",
  },
  {
    id: "glow",
    name: "Bright glow",
    value: "0 24px 46px rgba(14,165,233,0.35)",
  },
];

export const getPresetStyle = (preset) => normalizeNavStyle(preset.style || {});
