// src/constants/professions.js
export const PROFESSION_OPTIONS = [
  { value: "general", label: "General / Other" },
  { value: "salon", label: "Salon & Beauty" },
  { value: "spa_medspa", label: "Spa / Medspa" },
  { value: "barbershop", label: "Barbershop" },
  { value: "fitness", label: "Fitness & Personal Training" },
  { value: "yoga_pilates", label: "Yoga / Pilates Studio" },
  { value: "wellness", label: "Wellness & Massage" },
  { value: "therapy", label: "Therapy & Counseling" },
  { value: "medical_clinic", label: "Medical Clinic" },
  { value: "dental", label: "Dental" },
  { value: "chiropractic", label: "Chiropractic" },
  { value: "physiotherapy", label: "Physiotherapy" },
  { value: "tattoo_piercing", label: "Tattoo & Piercing" },
  { value: "photography", label: "Photography & Creative" },
  { value: "event_planning", label: "Event Planning" },
  { value: "education_tutoring", label: "Education & Tutoring" },
  { value: "music_lessons", label: "Music & Arts Lessons" },
  { value: "home_services", label: "Home Services / Trades" },
  { value: "cleaning", label: "Cleaning Services" },
  { value: "real_estate", label: "Real Estate" },
  { value: "legal", label: "Legal Services" },
  { value: "tax_accounting", label: "Tax & Accounting" },
  { value: "finance_advisory", label: "Finance & Advisory" },
  { value: "consulting", label: "Business Consulting" },
  { value: "it_services", label: "IT Services & MSP" },
  { value: "hr_recruiting", label: "HR & Recruiting" },
  { value: "auto_services", label: "Auto Services" },
  { value: "pet_care", label: "Pet Care & Grooming" },
  { value: "hospitality", label: "Hospitality & Tourism" },
  { value: "coaching", label: "Life / Career Coaching" },
  { value: "notary", label: "Notary & Admin Services" },
];
