// src/constants/professions.js
export const PROFESSION_OPTIONS = [
  { value: "recruiter", label: "Recruiter / Job Interview" },
  { value: "teacher", label: "Teacher / Parent Meeting" },
  { value: "fitness_coach", label: "Fitness Coach" },
  { value: "therapist", label: "Therapist / Counselor" },
  { value: "doctor", label: "Doctor / Medical" },
  { value: "photographer", label: "Photographer" },
  { value: "consultant", label: "Business Consultant" },
  { value: "lawyer", label: "Lawyer / Legal" },
  { value: "real_estate", label: "Real Estate Agent" },
  { value: "salon", label: "Salon / Beauty Professional" },
  { value: "tax_advisor", label: "Tax Advisor / Accountant" },
  { value: "financial_advisor", label: "Financial Advisor" },
  { value: "tutor", label: "Private Tutor" },
  { value: "event_planner", label: "Event Planner" },
  { value: "contractor", label: "Contractor / Trades" },
  { value: "coach_life", label: "Life Coach" },
  { value: "it_support", label: "IT Support" },
  { value: "repair_service", label: "Repair Service" },
  { value: "counselor", label: "Counselor / Guidance" },
  { value: "notary", label: "Notary" },
  { value: "custom", label: "Custom / Other" },
];
