const record = (id, type, slot, order, content, settings = {}) => ({ id, type, slot, order, enabled: true, content, settings: { createdInBuilder: true, starterBlueprint: "eldora-dark-original", source: "eldora-dark-original", ...settings } });
const media = (imageAlt) => ({ image: "", imageUrl: "", imageAlt });

export function createEldoraDarkOriginalHomeModules() {
  return [
    record("eldora-home-hero", "hero", "home.hero", 0, { eyebrow: "Service / Support", heading: "Comfort systems, made clearer.", subheading: "Use this cinematic field for the real service promise, property context, and strongest next step.", ...media("A cinematic wide image representing the company's work."), videoUrl: "", posterImage: "", primaryCta: { label: "Request service", href: "/contact" }, secondaryCta: { label: "Explore services", href: "/services" } }),
    record("eldora-home-trust", "trustRail", "home.afterHero", 1, { eyebrow: "Service context", heading: "Built around the work clients actually need.", intro: "Use honest capability labels here—not invented customers or logos.", items: ["Clear diagnostics", "Seasonal care", "Repair planning", "Upgrade guidance", "Property context", "Follow-through"].map((title, index) => ({ id: `eldora-trust-${index + 1}`, title, body: "Editable capability label" })) }, { presentation: "logo-ticker", claimsMode: "capabilities" }),
    record("eldora-home-services", "services", "home.primaryContent", 2, { eyebrow: "Services", heading: "Service paths for every season.", intro: "Current Services and prices remain management-owned.", source: "operational", items: [] }, { dataSource: "operational-services", presentation: "bento-services" }),
    record("eldora-home-bento-story", "featureStory", "home.primaryContent", 3, { eyebrow: "Current focus", heading: "Plan the next system decision with context.", body: "Use this card for an honest project, planning approach, or service principle—not fabricated performance results.", ...media("A cinematic project or planning image."), primaryCta: { label: "Start a conversation", href: "/contact" } }, { presentation: "bento-story" }),
    record("eldora-home-showcase", "featureStory", "home.afterServices", 4, { eyebrow: "Planning", heading: "Clearer next steps before pressure builds.", body: "Explain how the team diagnoses the current condition, presents options, and helps a client choose the next practical step.", ...media("A wide image showing project planning or completed work."), primaryCta: { label: "How we work", href: "/about" } }, { presentation: "cinematic-showcase" }),
    record("eldora-home-faq", "faq", "home.afterServices", 5, { eyebrow: "FAQ", heading: "Questions before the next visit.", intro: "Keep answers current and specific to the real service process.", items: [{ id: "eldora-faq-1", question: "What happens during the first visit?", answer: "Describe the real diagnostic or consultation process." }, { id: "eldora-faq-2", question: "How should a client prepare?", answer: "Add the practical information clients should have ready." }, { id: "eldora-faq-3", question: "Which properties do you support?", answer: "List only the property types the business actually serves." }, { id: "eldora-faq-4", question: "How are next steps explained?", answer: "Describe how findings, options, and timing are communicated." }] }),
    record("eldora-home-pricing", "pricing", "home.afterServices", 6, { eyebrow: "Planning options", heading: "Choose the right level of conversation.", intro: "These are editable marketing options; authoritative service prices stay in Services.", items: [{ id: "eldora-plan-1", title: "Diagnostic visit", price: "Current quote", body: "A focused first visit for a specific concern.", features: ["Current-condition review", "Clear findings", "Recommended next step"] }, { id: "eldora-plan-2", title: "Ongoing care", price: "Ask the team", body: "Recurring support where the business actually offers it.", features: ["Editable visit rhythm", "Current scheduling terms", "Service notes"] }, { id: "eldora-plan-3", title: "Project planning", price: "Custom", body: "A scoped conversation for a larger improvement.", features: ["Options review", "Scope discussion", "Written next steps"] }] }),
    record("eldora-home-contact-intro", "contactIntro", "home.beforeContact", 7, { eyebrow: "Start here", heading: "Bring the next service need into focus.", body: "Explain what information helps the team understand the property, timing, and current concern.", ...media("A dark editorial image introducing the inquiry process.") }),
    record("eldora-home-contact-details", "contactDetails", "home.beforeContact", 8, { heading: "Contact details", items: [{ id: "eldora-detail-phone", title: "Phone", body: "Add the business phone" }, { id: "eldora-detail-email", title: "Email", body: "Add the business email" }, { id: "eldora-detail-address", title: "Location", body: "Add the business address" }] }),
    record("eldora-home-hours", "hoursLocation", "home.beforeContact", 9, { eyebrow: "Hours", heading: "When to reach the team.", items: [{ id: "eldora-hours-weekday", title: "Monday – Friday", body: "Add real weekday hours" }, { id: "eldora-hours-weekend", title: "Weekend", body: "Add real weekend availability" }, { id: "eldora-hours-note", title: "Scheduling", body: "Add current scheduling guidance" }] }),
    record("eldora-home-map", "map", "home.beforeContact", 10, { eyebrow: "Location", heading: "Find the service base.", intro: "Add a supported address or map embed when location is useful.", query: "Add the business address", address: "Add the business address", embedUrl: "" }),
    record("eldora-home-contact-form", "contactForm", "home.beforeContact", 11, { eyebrow: "Request", heading: "Request the next conversation.", intro: "The existing Website Form handles this inquiry.", formKey: "contact", submitLabel: "Send request" }),
    record("eldora-home-cta", "bookingCta", "home.finalCta", 12, { eyebrow: "Next step", heading: "Make the next service decision clearer.", body: "Use the existing service and contact routes—no new transaction or lead backend is introduced.", primaryCta: { label: "Request service", href: "/contact" } }),
  ];
}
