const record = (id, type, slot, order, content, settings = {}) => ({ id, type, slot, order, enabled: true, content, settings: { createdInBuilder: true, starterBlueprint: "eldora-dark-original", source: "eldora-dark-original", ...settings } });
const media = (imageAlt) => ({ image: "", imageUrl: "", imageAlt });

export function createEldoraDarkOriginalHomeModules() {
  return [
    record("eldora-home-hero", "hero", "home.hero", 0, { eyebrow: "Home comfort, thoughtfully handled", heading: "Clarity for every season at home.", subheading: "A calm place to understand comfort concerns, review available services, and choose a sensible next step.", ...media("Technician inspecting an outdoor residential comfort unit with a flashlight."), imagePosition: { x: 68, y: 48 }, videoUrl: "", posterImage: "", primaryCta: { label: "Explore services", href: "/services" }, secondaryCta: { label: "Request a conversation", href: "/contact" } }),
    record("eldora-home-trust", "trustRail", "home.afterHero", 1, { intro: "A clear path from comfort question to informed next step.", items: ["Comfort questions", "System diagnostics", "Maintenance planning", "Clear next steps"].map((title, index) => ({ id: `eldora-trust-${index + 1}`, title })) }, { presentation: "capability-rail", claimsMode: "capabilities" }),
    record("eldora-home-services", "services", "home.primaryContent", 2, { eyebrow: "Connected service menu", heading: "Start with what your space needs.", intro: "Only active Services published in Schedulaa appear here, keeping descriptions, pricing, and booking paths aligned with operations.", source: "operational", items: [] }, { dataSource: "operational-services", presentation: "comfort-selector" }),
    record("eldora-home-process", "process", "home.afterHero", 3, { eyebrow: "How the conversation works", heading: "Diagnose first. Decide with context.", intro: "Adapt these editable steps to the business's verified service process.", items: [{ id: "eldora-process-1", title: "Understand the concern", body: "Begin with what changed, where comfort feels uneven, and what the system is doing now." }, { id: "eldora-process-2", title: "Inspect before recommending", body: "Use this space to explain the checks your team actually performs." }, { id: "eldora-process-3", title: "Make the next step clear", body: "Document the options and connect visitors to the existing request or booking workflow." }] }),
    record("eldora-home-maintenance", "featureStory", "home.afterHero", 4, { eyebrow: "Planning ahead", heading: "Comfort works better with a plan.", body: "Use this story to explain the business's confirmed maintenance approach without promising outcomes, timelines, or coverage that have not been verified.", ...media("Technician checking gauges during system maintenance."), primaryCta: { label: "Understand maintenance", href: "/maintenance" } }, { presentation: "cinematic-showcase" }),
    record("eldora-home-gallery", "gallery", "home.afterServices", 5, { eyebrow: "Systems in context", heading: "A closer look at comfort work.", intro: "Replace starter photography with verified project media when it is available.", items: [{ id: "eldora-gallery-1", title: "Diagnostic tools", ...media("Technician using diagnostic equipment.") }, { id: "eldora-gallery-2", title: "Home controls", ...media("Wall-mounted digital thermostat.") }, { id: "eldora-gallery-3", title: "Canadian-season context", ...media("Home during a snowy Canadian winter day.") }] }),
    record("eldora-home-areas", "serviceAreas", "home.afterServices", 6, { eyebrow: "Where service is available", heading: "Confirm whether your area is covered.", intro: "Service locations have not yet been verified for this starter.", items: [{ id: "eldora-area-pending", title: "Service-area details pending", body: "Replace this starter state with verified cities, neighbourhoods, or postal regions." }] }),
    record("eldora-home-reviews", "reviews", "home.afterServices", 7, { eyebrow: "Published feedback", heading: "What verified customers share.", intro: "Published Schedulaa review records appear here. No starter testimonials are included.", source: "operational", items: [] }, { dataSource: "operational-reviews" }),
    record("eldora-home-faq", "faq", "home.afterServices", 8, { eyebrow: "Good questions", heading: "Plan the conversation with confidence.", intro: "Edit these answers to reflect the business's confirmed process and policies.", items: [{ id: "eldora-faq-1", question: "What information should I include with a service request?", answer: "Describe the comfort concern, the type of space, and any system details you can safely identify." }, { id: "eldora-faq-2", question: "Where can I find current service and availability details?", answer: "Published services and their available next steps appear through the connected Schedulaa service records." }, { id: "eldora-faq-3", question: "How are service areas confirmed?", answer: "Only locations verified by the business should appear on this website." }] }),
    record("eldora-home-contact-form", "contactForm", "home.beforeContact", 9, { eyebrow: "Start with the details", heading: "Tell the team what is happening.", intro: "The existing WebsiteForm handles this inquiry; its recipient remains separately configured.", formKey: "contact" }),
    record("eldora-home-map", "map", "home.beforeContact", 10, { eyebrow: "Local service", heading: "Find the team.", intro: "This map uses the verified Company Profile address unless a manager enters a specific public location here.", address: "", query: "", embedUrl: "", primaryCta: { label: "Get directions", href: "" } }),
    record("eldora-home-cta", "cta", "home.finalCta", 11, { eyebrow: "A practical next step", heading: "Ready to make the comfort question clearer?", body: "Review the current service menu or send the team the information they need to begin.", primaryCta: { label: "View services", href: "/services" } }),
  ];
}
