const record = (id, type, slot, order, content, settings = {}) => ({ id, type, slot, order, enabled: true, content, settings: { createdInBuilder: true, starterBlueprint: "fieldcraft-original", source: "fieldcraft-original", ...settings } });
const media = (imageAlt) => ({ image: "", imageUrl: "", imageAlt });

export function createFieldcraftOriginalHomeModules() {
  return [
    record("field-home-hero", "hero", "home.hero", 0, { eyebrow: "Home Services / Trades", heading: "Built to show up, scope it cleanly, and finish right.", subheading: "Practical local service for repairs, installations, and project work that needs clearer communication from estimate to handoff.", ...media("Trade professional reviewing a residential project on site."), primaryCta: { label: "Request an estimate", href: "/contact" }, secondaryCta: { label: "View projects", href: "/projects" }, serviceAreas: ["Hamilton", "Burlington", "Oakville", "West GTA"], supportCards: [{ id: "field-hero-scope", title: "Typical scope", body: "Repairs, finish upgrades, and coordinated project work." }, { id: "field-hero-jobs", title: "Typical jobs", body: "Service lists, fixture installs, trim, finish, and renovation support." }], marqueeTopItems: ["Estimate clarity", "Repair visits", "Install upgrades", "Project sequencing", "Final walkthroughs"], marqueeBottomItems: ["Cleaner job sites", "Homeowner updates", "Service areas", "Finish detail", "Scope review"] }),
    record("field-home-services", "services", "home.primaryContent", 1, { eyebrow: "Service selector", heading: "Service paths with practical clarity.", intro: "Current offerings and prices remain managed in Services.", source: "operational", items: [] }, { dataSource: "operational-services", presentation: "practical-selector" }),
    record("field-home-proof", "stats", "home.afterHero", 2, { eyebrow: "Scope-first service", heading: "Useful proof without empty promises.", items: [{ id: "field-proof-estimate", value: "Clear", title: "Estimate path", body: "Set expectations before work begins." }, { id: "field-proof-area", value: "Local", title: "Service context", body: "Show the real areas your team covers." }, { id: "field-proof-work", value: "Practical", title: "Work pathways", body: "Repairs, installs, and project support." }, { id: "field-proof-handoff", value: "Documented", title: "Project handoff", body: "Close the work with useful next steps." }] }),
    record("field-home-before-after", "beforeAfter", "home.afterServices", 3, { eyebrow: "Before / After", heading: "A practical transformation.", intro: "Compare the starting condition with the finished project handoff.", items: [{ id: "field-before", title: "Before", category: "Starting condition", ...media("The project area before improvement work begins.") }, { id: "field-after", title: "After", category: "Finished handoff", ...media("The same project area after completed improvement work.") }] }, { presentation: "comparison-slider" }),
    record("field-home-projects", "portfolio", "home.afterServices", 4, { eyebrow: "Completed projects", heading: "Proof that feels local, not generic.", intro: "Use genuine completed-work images and concise project context.", items: ["Front hall refresh", "Basement service cleanup", "Kitchen upgrade handoff"].map((title, index) => ({ id: `field-project-${index + 1}`, title, category: ["Install & finish", "Repair & maintenance", "Project support"][index], body: ["A practical finish upgrade with clearer sequencing.", "A service issue corrected with a cleaner final handoff.", "Coordinated installation work with steady homeowner updates."][index], ...media(["Finished residential entry after repair and finish work.", "Completed home maintenance and repair project.", "Kitchen after coordinated installation and finish work."][index]) })) }, { presentation: "completed-work" }),
    record("field-home-process", "process", "home.afterHero", 5, { eyebrow: "How it works", heading: "From issue to finished handoff.", items: [{ id: "field-step-1", title: "Walk the issue", body: "Start with the problem, room, finish expectation, and timing pressure." }, { id: "field-step-2", title: "Scope the work", body: "Choose an estimate path, repair route, or phased sequence." }, { id: "field-step-3", title: "Do the work cleanly", body: "Arrive with context and communicate through the work." }, { id: "field-step-4", title: "Close with clarity", body: "Share completion notes and practical next steps." }] }),
    record("field-home-guide", "richText", "home.afterHero", 6, { eyebrow: "Homeowner guide", heading: "Notes that help the project day go better.", intro: "Editable homeowner guidance, not a separate blog.", items: [{ id: "field-guide-1", title: "What makes an estimate useful", body: "Explain the photos, dimensions, context, and finish expectations your team actually needs." }, { id: "field-guide-2", title: "Why sequencing matters", body: "Help clients understand access, preparation, and finish decisions before the workday." }, { id: "field-guide-3", title: "How to reduce project drag", body: "Share the real communication practices that keep work moving." }] }),
    record("field-home-team", "team", "home.primaryContent", 7, { eyebrow: "Project team", heading: "People who keep the site day steadier.", intro: "Introduce the real people responsible for scope, work, and communication.", items: [{ id: "field-team-1", title: "Project lead", role: "Estimates & sequencing", body: "Add a real team biography.", ...media("Portrait of the project lead.") }, { id: "field-team-2", title: "Client coordinator", role: "Scheduling & communication", body: "Add a real team biography.", ...media("Portrait of the client and scheduling coordinator.") }] }),
    record("field-home-reviews", "reviews", "home.afterServices", 8, { eyebrow: "Homeowner stories", heading: "Clearer work, reflected by clients.", intro: "Published Reviews remain management-owned.", source: "operational", items: [] }, { dataSource: "published-reviews", presentation: "local-proof" }),
    record("field-home-faq", "faq", "home.afterServices", 9, { eyebrow: "Questions", heading: "Start with the real home issue.", items: [{ id: "field-faq-1", question: "Can we request an estimate first?", answer: "Explain the real estimate and scope-review process." }, { id: "field-faq-2", question: "Do you handle small repairs and larger work?", answer: "Describe the actual range of work the company accepts." }, { id: "field-faq-3", question: "Which areas do you serve?", answer: "List only the current service area." }] }),
    record("field-home-contact-intro", "contactIntro", "home.beforeContact", 10, { eyebrow: "Request estimate", heading: "Ready to get the scope cleaner?", body: "Share the repair list, installation plan, or project that needs a clearer next step.", ...media("Trade professional reviewing project details with a homeowner.") }),
    record("field-home-contact-details", "contactDetails", "home.beforeContact", 11, { heading: "Contact the team", items: [{ id: "field-detail-phone", title: "Phone", body: "Add the business phone" }, { id: "field-detail-email", title: "Email", body: "Add the business email" }, { id: "field-detail-address", title: "Base", body: "Add the business address" }] }),
    record("field-home-hours", "hoursLocation", "home.beforeContact", 12, { eyebrow: "Hours", heading: "Plan the first conversation.", items: [{ id: "field-hours-weekday", title: "Weekdays", body: "Add real weekday hours" }, { id: "field-hours-weekend", title: "Weekend", body: "Add real weekend hours" }, { id: "field-hours-note", title: "Estimate visits", body: "Add current scheduling guidance" }] }),
    record("field-home-service-areas", "serviceAreas", "home.beforeContact", 13, { eyebrow: "Service area", heading: "Where the team works.", items: ["Hamilton", "Burlington", "Oakville", "West GTA"].map((title, index) => ({ id: `field-area-${index + 1}`, title, body: "Confirm current coverage before publishing." })) }),
    record("field-home-map", "map", "home.beforeContact", 14, { eyebrow: "Local service", heading: "Find the service base.", intro: "Add the supported address or service-area map embed.", query: "Add the service address", address: "Add the service address", embedUrl: "" }),
    record("field-home-contact-form", "contactForm", "home.beforeContact", 15, { heading: "Tell us what needs attention.", intro: "The existing Website Form handles this estimate inquiry.", formKey: "contact", submitLabel: "Send estimate request" }),
    record("field-home-cta", "bookingCta", "home.finalCta", 16, { eyebrow: "A practical next step", heading: "Start with a clearer project scope.", body: "Share the work, the timing, and the finish expectation.", primaryCta: { label: "Request an estimate", href: "/contact" } }),
  ];
}
