const record = (id, type, slot, order, content, settings = {}) => ({ id, type, slot, order, enabled: true, content, settings: { createdInBuilder: true, starterBlueprint: "motion-editorial-original", source: "motion-editorial-original", ...settings } });
const media = (imageAlt) => ({ image: "", imageUrl: "", imageAlt });

export function createMotionEditorialOriginalHomeModules() {
  return [
    record("motion-home-hero", "hero", "home.hero", 0, { eyebrow: "Service / Studio", heading: "Comfort, considered in motion.", subheading: "Use this full-screen editorial field for the real promise, service context, and strongest next step.", ...media("A wide editorial image representing the company and its work."), videoUrl: "", posterImage: "", primaryCta: { label: "Request service", href: "/contact" }, secondaryCta: { label: "Explore services", href: "/services" } }),
    record("motion-home-explore", "trustRail", "home.afterHero", 1, { eyebrow: "Explore", heading: "Four ways the work meets the moment.", intro: "Editable service markers support the operational directory without replacing it.", items: ["Repair", "Maintenance", "Upgrades", "Planning"].map((title, index) => ({ id: `motion-explore-${index + 1}`, title, body: ["Describe the real urgent-service pathway.", "Describe the real recurring-care pathway.", "Describe the real improvement pathway.", "Describe the real consultation pathway."][index] })), ...media("A tall editorial detail image representing the service experience.") }),
    record("motion-home-story", "featureStory", "home.afterHero", 2, { eyebrow: "About", heading: "A story that unfolds as the page moves.", intro: "Three editable chapters move through one pinned editorial field on desktop.", primaryCta: { label: "Learn more", href: "/about" }, items: [{ id: "motion-story-1", title: "Our story", body: "Explain why the company exists and the standard it brings to the work.", ...media("Editorial image introducing the company's story.") }, { id: "motion-story-2", title: "Our process", body: "Explain how a service visit progresses with clarity.", ...media("Editorial image showing the company's service process.") }, { id: "motion-story-3", title: "Our team", body: "Introduce how the real team coordinates the client experience.", ...media("Editorial image showing the people behind the work.") }] }, { presentation: "pinned-story" }),
    record("motion-home-services", "services", "home.primaryContent", 3, { eyebrow: "Menu", heading: "Popular services.", intro: "Current Services and prices remain management-owned.", source: "operational", items: [] }, { dataSource: "operational-services", presentation: "editorial-directory" }),
    record("motion-home-hours", "hoursLocation", "home.beforeContact", 4, { eyebrow: "Service hours", heading: "Know when to reach the team.", intro: "Add the actual operating hours and location context.", ...media("Editorial exterior or workspace image for service hours."), items: [{ id: "motion-hours-weekday", title: "Monday – Friday", body: "Add real weekday hours" }, { id: "motion-hours-weekend", title: "Saturday", body: "Add real weekend hours" }, { id: "motion-hours-note", title: "Appointments", body: "Add current scheduling guidance" }] }),
    record("motion-home-reviews", "reviews", "home.afterServices", 5, { eyebrow: "Client stories", heading: "What people remember.", intro: "Published Reviews remain management-owned.", source: "operational", items: [] }, { dataSource: "published-reviews", presentation: "editorial-stories" }),
    record("motion-home-contact-intro", "contactIntro", "home.beforeContact", 6, { eyebrow: "Start here", heading: "Bring the next need into focus.", body: "Explain what information helps the team route a new inquiry.", ...media("Editorial image introducing the contact conversation.") }),
    record("motion-home-contact-details", "contactDetails", "home.beforeContact", 7, { heading: "Contact details", items: [{ id: "motion-detail-phone", title: "Phone", body: "Add the business phone" }, { id: "motion-detail-email", title: "Email", body: "Add the business email" }, { id: "motion-detail-address", title: "Location", body: "Add the business address" }] }),
    record("motion-home-map", "map", "home.beforeContact", 8, { eyebrow: "Location", heading: "Find the studio.", intro: "Add the supported address or map embed.", query: "Add the business address", address: "Add the business address", embedUrl: "" }),
    record("motion-home-contact-form", "contactForm", "home.beforeContact", 9, { heading: "Request a conversation.", intro: "The existing Website Form handles this inquiry.", formKey: "contact", submitLabel: "Send request" }),
    record("motion-home-cta", "bookingCta", "home.finalCta", 10, { eyebrow: "Next step", heading: "Make the next visit feel clearer.", body: "Use the existing service and contact routes—no new transaction flow is introduced.", primaryCta: { label: "Request service", href: "/contact" } }),
  ];
}
